# Generated by Django 4.2.7 on 2024-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseprojet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="user_photos/"),
        ),
    ]
