# Generated by Django 4.2.13 on 2024-06-07 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("databaseprojet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Supervisor", "Supervisor"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="speciality_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="databaseprojet.speciality",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
