# Generated by Django 5.0.6 on 2024-06-04 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseprojet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Number_of_credits', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Speciality_id', models.IntegerField()),
                ('coefficient', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('coefficient_lectures', models.IntegerField()),
                ('coefficient_PW', models.IntegerField()),
                ('coefficient_DW', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Score', models.FloatField()),
                ('absence_number', models.IntegerField()),
                ('course_type', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Supervisor')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_id', models.IntegerField(choices=[(1, 'Informatique et réseaux'), (2, 'Automatique et systèmes embarqués'), (3, 'Génie Textile et Fibres'), (4, 'Génie Mécanique'), (5, 'Génie industriel')], unique=True)),
                ('name', models.CharField(max_length=255)),
                ('responsible_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='../Media/photos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=255)),
                ('student_id', models.IntegerField(unique=True)),
                ('year', models.IntegerField()),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.roles')),
                ('speciality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.speciality')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='absence',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.module'),
        ),
        migrations.AddField(
            model_name='score',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.course'),
        ),
        migrations.AddField(
            model_name='module',
            name='speciality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.speciality'),
        ),
        migrations.AddField(
            model_name='score',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.user'),
        ),
        migrations.AddField(
            model_name='course_type',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.user'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseprojet.user'),
        ),
    ]
