# Generated by Django 4.2.7 on 2024-06-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("databaseprojet", "0002_alter_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="coefficient_DW",
        ),
        migrations.RemoveField(
            model_name="course",
            name="coefficient_PW",
        ),
        migrations.RemoveField(
            model_name="course",
            name="coefficient_lectures",
        ),
        migrations.AddField(
            model_name="course",
            name="teacher_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
