# Generated by Django 4.2.7 on 2024-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "databaseprojet",
            "0002_absence_course_course_type_module_roles_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="name",
            field=models.CharField(
                choices=[(1, "Student"), (2, "Teacher"), (3, "Supervisor")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
