# Generated by Django 4.2.13 on 2024-06-10 20:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("databaseprojet", "0002_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("jours", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseprojet.course",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="absence", old_name="course_id", new_name="course",
        ),
        migrations.DeleteModel(name="Hours",),
    ]
