# Generated by Django 4.2.7 on 2024-06-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseprojet", "0003_alter_roles_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="name",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Supervisor", "Supervisor"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(upload_to="user_photos/"),
        ),
    ]
