# Generated by Django 4.2.13 on 2024-06-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("databaseprojet", "0004_alter_roles_id_alter_roles_name"),
        ("databaseprojet", "0004_alter_roles_id_alter_roles_name_alter_user_photo"),
    ]

    operations = []
